build:
	CGO_ENABLED=0 GOOS=windows go build -o bin/server.exe github.com/ArchangelSDY/msal-login-forwarder/cmd/server
	CGO_ENABLED=0 go build -o bin/client github.com/ArchangelSDY/msal-login-forwarder/cmd/client
